#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 27 01:11:54 2020

@author: vamsi
"""
import pandas as pd
import os
trade_days=[]

for files in os.walk("/tmp/cme"):
    for filename in files[2]:
        trade_days.append(filename[:8])

trade_days.sort()
con=pd.DataFrame(columns = ['Month', 'Globex', 'Open OutCry', 'Clear Port', 'Total Volume',
       'Block Trades', 'EFP', 'EFR', 'EFS', 'TAS', 'Deliveries', 'At Close',
       'Change', 'Trade Day'])

for td in trade_days:
    print(td)
    df = pd.read_excel(r'/tmp/cme/'+td+'.xls',skiprows =4,header=1)
    #slice to first occurrence of "TOTALS"
    df=df.loc[: df[(df['Month'] == 'TOTALS')].index[0]-1, :]
    df['Trade Day']=td
    con=con.append(df,ignore_index=True)
    
con.to_csv('consolidated_rb_oi.csv',index=False)